### PR TITLE
Test PR comments

### PR DESCRIPTION
**Pull request by hemanthgk10**
Signed-off-by: Hemanth Gokavarapu <hemanth@soluble.ai>

### CODE REVIEW

**Comment by hemanthgk10** [comment]
<details>
<summary> Impact: <b> 1 resource is impacted </b> </summary>

### `module.db.aws_security_group_rule.cidr_ingress[0]`

This change affects the following resources:
| COUNT |      TYPE       |    RULE ID    |        SEVERITY        |                      MESSAGE                       | AWS ACCOUNT/ALIAS |
|-------|-----------------|---------------|------------------------|----------------------------------------------------|-------------------|
|     1 | aws_rds_cluster | aws.port_open | :yellow_circle: medium | Security group rule is open to public IP addresses | soluble-lab       |

<details>
<summary>Plan snippet</summary>

```
  # module.db.aws_security_group_rule.cidr_ingress[0] will be created
  + resource "aws_security_group_rule" "cidr_ingress" {
      + cidr_blocks              = [
          + "192.168.1.0/24",
        ]
      + description              = "From allowed CIDRs"
      + from_port                = 5432
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = "sg-0b806fda083e3c54b"
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 5432
      + type                     = "ingress"
    }
```

</details>



</details>

**Comment by devops-blogger** [comment]
@deepsourcebot help

**Comment by devops-blogger** [comment]
@soluble help

**Comment by hemanthgk10** [comment]
@iacbot help

**Comment by hemanthgk10** [comment]
@iacbot autofix 928ad2s234sad

**Pull request closed without merging**
